part of 'auth_bloc.dart';

@immutable
abstract class AuthState {}

class Initial extends AuthState {}

class Loading extends AuthState {}

class Authenticated extends AuthState {
  final AutogeneratedModel model;

  Authenticated({required this.model});

  @override
  List<Object> get props => [model];
}

class Unauthenticated extends AuthState {}

class ErrorState extends AuthState {
  final String message;

  ErrorState({required this.message});

  @override
  List<Object> get props => [message];
}
