
class Autogenerated {
  Tokens tokens;
  User user;

  Autogenerated({required this.tokens, required this.user});

  @override
  List<Object> get props => [tokens, user];
}

class AutogeneratedModel extends Autogenerated {
  AutogeneratedModel({required Tokens tokens, required User user})
      : super(tokens: tokens, user: user);

  factory AutogeneratedModel.fromJson(Map<String, dynamic> json) {
    return AutogeneratedModel(
        tokens: Tokens.fromJson(json['tokens']),
        user: User.fromJson(json['user']));
  }

  Map<String, dynamic> toJson() {
    return {'tokens': tokens, 'user': user};
  }
}

class Tokens {
  String accessToken;
  String refreshToken;

  Tokens({required this.accessToken, required this.refreshToken});

  factory Tokens.fromJson(Map<String, dynamic> json) {
    return Tokens(
      accessToken: json['accessToken'],
      refreshToken: json['refreshToken'],
    );
  }

  Map<String, dynamic> toJson() {
    return {'accessToken': accessToken, 'refreshToken': refreshToken};
  }
}

class User {
  int id;
  String email;
  String nickname;

  User({required this.id, required this.email, required this.nickname});

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'],
      email: json['email'],
      nickname: json['nickname'],
    );
  }

  Map<String, dynamic> toJson() {
    return {'id': id, 'email': email, 'nickname': nickname};
  }
}
